<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <!-- 
        Promise解决了什么问题：https://blog.csdn.net/qq_38421628/article/details/121509196
        一、Promise应用场景
            Promise 是异步编程的一种解决方案：
            从语法上讲，promise是一个对象，从它可以获取异步操作的消息；
            从本意上讲，它是承诺，承诺它过一段时间会给你一个结果。
            promise有三种状态： pending(等待态)，fulfiled(成功态)，rejected(失败态)；状态一旦改变，就不会再变。
            创造promise实例后，它会立即执行。 
        二、Promise是什么
            1、主要用于异步计算 
            2、可以将异步操作队列化，按照期望的顺序执行，返回符合预期的结果 
            3、可以在对象之间传递和操作promise，帮助我们处理队列 
            4、Promise可以用来避免异步操作函数里的嵌套回调（callback hell）问题，
                因为解决异步最直接的方法是回调嵌套，将后一个的操作放在前一个操作的异步回调里，但如果操作多了，就会有很多层的嵌套。 
        三、为什么会有Promise
            异步回调的问题：
            ● 之前处理异步是通过纯粹的回调函数的形式进行处理 
            ● 很容易进入到回调地狱中，剥夺了函数return的能力 
            ● 问题可以解决，但是难以读懂，维护困难 
            ● 稍有不慎就会踏入回调地狱 - 嵌套层次深，不好维护
        四、ES6里Promise解决了什么问题
            1、promise本质上是给出了一种异步任务同步写法的解决方案，然后才是解决回调地狱问题； 
            2、其中还会涉及微任务宏任务问题；先执行宏任务，再执行微任务 
            3、anysc await 其实本质是promise.then的执行结果；但是其更完美的体现了异步任务同步执行的形式
    -->
    <script>
        // Promise
        // Promise是JS解决异步编程的方法之一，其英文意思是承诺。
        //     在程序中可理解为等一段时间就会执行，等一段时间就是JS中的异步。
        //     异步是指需要比较长的时间才能执行完成的任务，例如网络请求，读取文件等。
        //     Promise是一个实例对象，可从中获取异步处理的结果。

        // Promise有3种状态，
        //     分别是pending(进行中)、fulfilled(已成功)、rejected(已失败)。
        //     只有异步操作可改变Promise的状态，其他操作都无法改变。
        //     并且状态改变后就不会再变，
        //     只能是从pending到fulfiled或pending到rejected，这也是Promise一个比较鲜明的特点。



        // resolve将状态从pending变为fulfiled，成功时调用。
        // reject将状态从pending变为rejected，失败时调用
        // Promise {<pending>} ==> fulfiled | rejected
        function RunPromise(num, time) {
            return new Promise((resolve, reject) => {
                console.log("开始执行");
                if(num % 2 === 0){
                    setTimeout(function(){
                        resolve(`偶数时调用resolve, 此时num为${num}`);
                    },time)
                }
                else{
                    setTimeout(function(){
                        reject(new Error(`奇数数时调用reject, 此时num为${num}`));  
                    },time)
                }
            })  
        }
        // console.log(RunPromise(1, 1000).then(v => console.log(v)).catch(e => console.log(e)))

        // RunPromise(22, 20000).then(res => {
        //     // console.log("then的第一个参数执行");
        //     // console.log(res);
        //     // console.log(newres);
        // }, error => {
        //     // console.log("then的第二个参数执行");
        //     // console.log(error);
        // }).catch(error => {
        //     // console.log("error");
        //     // console.log(error);
        // });

        // 上面例子中，RunPromise()调用resolve，then()的第一个参数对应回调，状态从pending改成fulfilled，且状态不会再改变。
        // 在then()中，newres这个变量尚未定义，因此程序出错，其异常在catch()被捕获。
        // 一般来说，then()使用第一个参数即可，因为catch()跟then()的第二个参数一样，还能捕获到异常







        

        // ES6声明构造函数
        class MyPromise {
            constructor(implement) {
                this.status = "pending"; // 初始化状态为pending
                this.res = null; // 成功时的值
                this.error = null; // 失败时的值
                this.resolveCallbacks = []; // 成功时回调的处理函数
                this.rejectCallbacks = []; // 失败时回调的处理函数
                const resolve = res => {
                    // resolve的作用只是将状态从pending转为fulfilled，并将成功时的值存在this.res
                    if (this.status === "pending") {
                        this.status = "fulfilled";
                        this.res = res;
                        this.resolveCallbacks.forEach(fn => fn()) // 循环执行成功处理函数
                    }
                };
                const reject = error => {
                    // reject的作用只是将状态从pending转为rejected，并将失败时的值存在this.error
                    if (this.status === "pending") {
                        this.status = "rejected";
                        this.error = error;
                        this.rejectCallbacks.forEach(fn => fn()) // 循环执行失败处理函数
                    }
                };
                // 程序报错时会执行reject，所以在这里加上错误捕获，直接执行reject
                try {
                    implement(resolve, reject);
                } catch (err) {
                    reject(err);
                }
            }
            then(onFulfilled, onRejected){
                // 当状态为fulfilled时，调用onFulfilled并传入成功时的值
                if(this.status === "fulfilled"){
                    onFulfilled(this.res)
                }
                // 当状态为rejected时，调用onRejected并传入成功时的值
                if(this.status === "rejected"){
                    onRejected(this.error)
                }
                // 当状态为pending时，说明这时还没有调用到resolve或reject
                // 在这里把成功函数和失败函数存至相应的数组中，不做执行操作只做存储操作

                // resolve在setTimeout()中使用，这时候在then()里，状态还是pending，那就没办法调用到onFulfilled

                if (this.status === "pending") {
                    this.resolveCallbacks.push(() => onFulfilled(this.res));
                    this.rejectCallbacks.push(() => onRejected(this.error));
                }
            }
        } 
        // new Promise((resolve, reject) => {})

        // const mp = new MyPromise(function(res, rej) {  res(111) })
        // console.log(mp)
        
        // new MyPromise((resolve, reject) => {
        //     console.log("开始执行");
        //     setTimeout(() => {
        //         resolve("执行resolve");
        //     }, 2000);
        // }).then(res => console.log(res));









        //  实现链式调用: https://segmentfault.com/a/1190000022294224#comment-area
        class MyPromise2 {
            constructor(implement) {
                this.status = "pending"; // 初始化状态为pending
                this.res = null; // 成功时的值
                this.error = null; // 失败时的值
                this.resolveCallbacks = []; // 成功时回调的处理函数
                this.rejectCallbacks = []; // 失败时回调的处理函数
                const resolve = res => {
                    // resolve的作用只是将状态从pending转为fulfilled，并将成功时的值存在this.res
                    if (this.status === "pending") {
                        this.status = "fulfilled";
                        this.res = res;
                        this.resolveCallbacks.forEach(fn => fn()) // 循环执行成功处理函数
                    }
                };
                const reject = error => {
                    // reject的作用只是将状态从pending转为rejected，并将失败时的值存在this.error
                    if (this.status === "pending") {
                        this.status = "rejected";
                        this.error = error;
                        this.rejectCallbacks.forEach(fn => fn()) // 循环执行失败处理函数
                    }
                };
                // 程序报错时会执行reject，所以在这里加上错误捕获，直接执行reject
                try {
                    implement(resolve, reject);
                } catch (err) {
                    reject(err);
                }
            }
            then(onFulfilled, onRejected) {
                // 如果onRejected不是函数，就直接抛出错误
                onFulfilled = typeof onFulfilled === "function" ? onFulfilled : res => res;
                onRejected = typeof onRejected === "function" ? onRejected : err => { throw err; };
                const nextPromise = new MyPromise((resolve, reject) => {
                    function RecursionPromise(nextPromise, x, resolve, reject) {
                        if (nextPromise === x) return false;
                        let flag;
                        if (x !== null && (typeof x === "object" || typeof x === "function")) {
                            try {
                                let then = x.then;
                                if (typeof then === "function") {
                                    then.call(x, y => {
                                        if (flag) return false;
                                        flag = true;
                                        // 这里说明Promise对象resolve之后的结果仍然是Promise，那么继续递归解析
                                        RecursionPromise(nextPromise, y, resolve, reject);
                                    }, error => {
                                        if (flag) return false;
                                        flag = true;
                                        reject(error);
                                    });
                                } else {
                                    resolve(x);
                                }
                            } catch (e) {
                                if (flag) return false;
                                flag = true;
                                reject(e);
                            }
                        } else {
                            resolve(x);
                        }
                    }
                    if (this.status === "fulfilled") {
                        // 解决异步问题
                        setTimeout(() => {
                            const x = onFulfilled(this.res);
                            RecursionPromise(nextPromise, x, resolve, reject);
                        }, 0);
                    }
                    if (this.status === "rejected") {
                        setTimeout(() => {
                            const x = onRejected(this.error);
                            RecursionPromise(nextPromise, x, resolve, reject);
                        }, 0);
                    }
                    if (this.status === "pending") {
                        this.resolveCallbacks.push(() => {
                            setTimeout(() => {
                                const x = onFulfilled(this.res);
                                RecursionPromise(nextPromise, x, resolve, reject);
                            }, 0);
                        });
                        this.rejectCallbacks.push(() => {
                            setTimeout(() => {
                                const x = onRejected(this.error);
                                RecursionPromise(nextPromise, x, resolve, reject);
                            }, 0);
                        });
                    }
                });
                return nextPromise;
            }
        }
        // 链式调用
        // new MyPromise2((resolve, reject) => {
        //     console.log("开始执行");
        //     setTimeout(() => {
        //         resolve("执行resolve");
        //     }, 1000); 
        // }).then(res => {
        //     console.log(res)
            
        //     new MyPromise2((resolve, reject) => {
        //         setTimeout(() => {
        //             resolve("执行resolve2222");
        //         }, 1000); 
        //     }).then(res2 => {
        //         console.log(res2)
                
        //         new MyPromise2((resolve, reject) => {
        //             setTimeout(() => {
        //                 resolve("执行resolve333333");
        //             }, 1000); 
        //         }).then(res3 => {
        //             console.log(res3) 
        //         })
        //     })
        // }) 


        new MyPromise2((resolve, reject) => {
            console.log("开始执行");
            setTimeout(() => {
                resolve("执行resolve");
            }, 2000); 
        }).then(res => {
            return res
        }).then(res2 => {
            console.log(res2)
        })

    </script>
</body>
</html>